'use strict';

/**
 * Mock Salesforce account data for running the app without a live SF connection.
 * Covers all five action types: Add, Remove, Reclassify, No Change, Ignore.
 */
const RAW_MOCK_ACCOUNTS = [
  // ── ADD (no tier, qualifies for one) ────────────────────────────────────────
  { Id: '0010MOCK0001', Name: 'Acme Cloud Solutions',       ABX_Tier__c: null,     Fit_Score_Total__c: 12, Account_Intent__c: 'High',   Account_Stage__c: 'Prospect',    Marketplace_Prospect__c: false, Consulting_IT_Filter_Flow__c: false, Company_isDefunct__c: 'false', Qualified_Out_Detail__c: null, ParentId: null, Entered_Closed_Lost_Date__c: null },
  { Id: '0010MOCK0002', Name: 'Stratus Analytics Inc',      ABX_Tier__c: null,     Fit_Score_Total__c: 11, Account_Intent__c: 'Medium', Account_Stage__c: 'Prospect',    Marketplace_Prospect__c: false, Consulting_IT_Filter_Flow__c: false, Company_isDefunct__c: 'false', Qualified_Out_Detail__c: null, ParentId: null, Entered_Closed_Lost_Date__c: null },
  { Id: '0010MOCK0003', Name: 'NexGen Data Corp',           ABX_Tier__c: null,     Fit_Score_Total__c: 9,  Account_Intent__c: 'High',   Account_Stage__c: 'Prospect',    Marketplace_Prospect__c: true,  Consulting_IT_Filter_Flow__c: false, Company_isDefunct__c: 'false', Qualified_Out_Detail__c: null, ParentId: null, Entered_Closed_Lost_Date__c: null },
  { Id: '0010MOCK0004', Name: 'Vertex Engineering',         ABX_Tier__c: null,     Fit_Score_Total__c: 11, Account_Intent__c: 'Low',    Account_Stage__c: 'Prospect',    Marketplace_Prospect__c: false, Consulting_IT_Filter_Flow__c: false, Company_isDefunct__c: 'false', Qualified_Out_Detail__c: null, ParentId: null, Entered_Closed_Lost_Date__c: null },
  { Id: '0010MOCK0005', Name: 'BlueSky Technologies',       ABX_Tier__c: null,     Fit_Score_Total__c: 8,  Account_Intent__c: 'High',   Account_Stage__c: 'Prospect',    Marketplace_Prospect__c: false, Consulting_IT_Filter_Flow__c: false, Company_isDefunct__c: 'false', Qualified_Out_Detail__c: null, ParentId: null, Entered_Closed_Lost_Date__c: null },
  { Id: '0010MOCK0006', Name: 'Quantum Leap Systems',       ABX_Tier__c: null,     Fit_Score_Total__c: 10, Account_Intent__c: 'High',   Account_Stage__c: 'Closed Lost', Marketplace_Prospect__c: false, Consulting_IT_Filter_Flow__c: false, Company_isDefunct__c: 'false', Qualified_Out_Detail__c: null, ParentId: null, Entered_Closed_Lost_Date__c: '2024-06-15' },

  // ── REMOVE (has tier, no longer qualifies) ──────────────────────────────────
  { Id: '0010MOCK0007', Name: 'Orbital Systems Ltd',        ABX_Tier__c: 'Tier 2', Fit_Score_Total__c: 10, Account_Intent__c: 'High',   Account_Stage__c: 'Closed Lost', Marketplace_Prospect__c: false, Consulting_IT_Filter_Flow__c: false, Company_isDefunct__c: 'false', Qualified_Out_Detail__c: null, ParentId: null, Entered_Closed_Lost_Date__c: '2025-09-15' },
  { Id: '0010MOCK0008', Name: 'Pacific Ventures',           ABX_Tier__c: 'Tier 1', Fit_Score_Total__c: 12, Account_Intent__c: 'High',   Account_Stage__c: 'Customer',    Marketplace_Prospect__c: false, Consulting_IT_Filter_Flow__c: false, Company_isDefunct__c: 'false', Qualified_Out_Detail__c: null, ParentId: null, Entered_Closed_Lost_Date__c: null },
  { Id: '0010MOCK0009', Name: 'Meridian Software',          ABX_Tier__c: 'Tier 3', Fit_Score_Total__c: 3,  Account_Intent__c: 'None',   Account_Stage__c: 'Prospect',    Marketplace_Prospect__c: false, Consulting_IT_Filter_Flow__c: false, Company_isDefunct__c: 'false', Qualified_Out_Detail__c: null, ParentId: null, Entered_Closed_Lost_Date__c: null },
  { Id: '0010MOCK0010', Name: 'Redline Infrastructure',     ABX_Tier__c: 'Tier 2', Fit_Score_Total__c: 9,  Account_Intent__c: 'High',   Account_Stage__c: 'Prospect',    Marketplace_Prospect__c: false, Consulting_IT_Filter_Flow__c: false, Company_isDefunct__c: 'false', Qualified_Out_Detail__c: 'Not a good fit for IDP',  ParentId: null, Entered_Closed_Lost_Date__c: null },

  // ── RECLASSIFY (has tier, different from recommendation) ────────────────────
  { Id: '0010MOCK0011', Name: 'Apex Digital Group',         ABX_Tier__c: 'Tier 3', Fit_Score_Total__c: 11, Account_Intent__c: 'High',   Account_Stage__c: 'Prospect',    Marketplace_Prospect__c: false, Consulting_IT_Filter_Flow__c: false, Company_isDefunct__c: 'false', Qualified_Out_Detail__c: null, ParentId: null, Entered_Closed_Lost_Date__c: null },
  { Id: '0010MOCK0012', Name: 'TerraCloud Inc',             ABX_Tier__c: 'Tier 1', Fit_Score_Total__c: 9,  Account_Intent__c: 'Medium', Account_Stage__c: 'Prospect',    Marketplace_Prospect__c: false, Consulting_IT_Filter_Flow__c: false, Company_isDefunct__c: 'false', Qualified_Out_Detail__c: null, ParentId: null, Entered_Closed_Lost_Date__c: null },
  { Id: '0010MOCK0013', Name: 'Cascade Dynamics',           ABX_Tier__c: 'Tier 2', Fit_Score_Total__c: 8,  Account_Intent__c: 'High',   Account_Stage__c: 'Prospect',    Marketplace_Prospect__c: false, Consulting_IT_Filter_Flow__c: false, Company_isDefunct__c: 'false', Qualified_Out_Detail__c: null, ParentId: null, Entered_Closed_Lost_Date__c: null },
  { Id: '0010MOCK0014', Name: 'Summit Analytics',           ABX_Tier__c: 'Tier 1', Fit_Score_Total__c: 11, Account_Intent__c: 'Medium', Account_Stage__c: 'Prospect',    Marketplace_Prospect__c: false, Consulting_IT_Filter_Flow__c: false, Company_isDefunct__c: 'false', Qualified_Out_Detail__c: null, ParentId: null, Entered_Closed_Lost_Date__c: null },

  // ── NO CHANGE (current tier already correct) ────────────────────────────────
  { Id: '0010MOCK0015', Name: 'Horizon Systems',            ABX_Tier__c: 'Tier 1', Fit_Score_Total__c: 12, Account_Intent__c: 'High',   Account_Stage__c: 'Prospect',    Marketplace_Prospect__c: false, Consulting_IT_Filter_Flow__c: false, Company_isDefunct__c: 'false', Qualified_Out_Detail__c: null, ParentId: null, Entered_Closed_Lost_Date__c: null },
  { Id: '0010MOCK0016', Name: 'CloudBase Corp',             ABX_Tier__c: 'Tier 2', Fit_Score_Total__c: 11, Account_Intent__c: 'Medium', Account_Stage__c: 'Prospect',    Marketplace_Prospect__c: false, Consulting_IT_Filter_Flow__c: false, Company_isDefunct__c: 'false', Qualified_Out_Detail__c: null, ParentId: null, Entered_Closed_Lost_Date__c: null },
  { Id: '0010MOCK0017', Name: 'Stellar Infrastructure',     ABX_Tier__c: 'Tier 3', Fit_Score_Total__c: 9,  Account_Intent__c: 'Medium', Account_Stage__c: 'Prospect',    Marketplace_Prospect__c: false, Consulting_IT_Filter_Flow__c: false, Company_isDefunct__c: 'false', Qualified_Out_Detail__c: null, ParentId: null, Entered_Closed_Lost_Date__c: null },
  { Id: '0010MOCK0018', Name: 'Atomic Data Services',       ABX_Tier__c: 'Tier 3', Fit_Score_Total__c: 8,  Account_Intent__c: 'High',   Account_Stage__c: 'Prospect',    Marketplace_Prospect__c: false, Consulting_IT_Filter_Flow__c: false, Company_isDefunct__c: 'false', Qualified_Out_Detail__c: null, ParentId: null, Entered_Closed_Lost_Date__c: null },
  { Id: '0010MOCK0019', Name: 'Polaris Cloud',              ABX_Tier__c: 'Tier 2', Fit_Score_Total__c: 9,  Account_Intent__c: 'High',   Account_Stage__c: 'Prospect',    Marketplace_Prospect__c: false, Consulting_IT_Filter_Flow__c: false, Company_isDefunct__c: 'false', Qualified_Out_Detail__c: null, ParentId: null, Entered_Closed_Lost_Date__c: null },

  // ── IGNORE (below threshold or excluded, no existing tier) ──────────────────
  { Id: '0010MOCK0020', Name: 'Static Networks',            ABX_Tier__c: null,     Fit_Score_Total__c: 3,  Account_Intent__c: 'None',   Account_Stage__c: 'Prospect',    Marketplace_Prospect__c: false, Consulting_IT_Filter_Flow__c: false, Company_isDefunct__c: 'false', Qualified_Out_Detail__c: null, ParentId: null, Entered_Closed_Lost_Date__c: null },
  { Id: '0010MOCK0021', Name: 'LegacySoft Inc',             ABX_Tier__c: null,     Fit_Score_Total__c: 7,  Account_Intent__c: 'Low',    Account_Stage__c: 'Prospect',    Marketplace_Prospect__c: false, Consulting_IT_Filter_Flow__c: false, Company_isDefunct__c: 'false', Qualified_Out_Detail__c: null, ParentId: null, Entered_Closed_Lost_Date__c: null },
  { Id: '0010MOCK0022', Name: 'Defunct Labs',               ABX_Tier__c: null,     Fit_Score_Total__c: 11, Account_Intent__c: 'High',   Account_Stage__c: 'Prospect',    Marketplace_Prospect__c: false, Consulting_IT_Filter_Flow__c: false, Company_isDefunct__c: 'true',  Qualified_Out_Detail__c: null, ParentId: null, Entered_Closed_Lost_Date__c: null },
];

module.exports = { RAW_MOCK_ACCOUNTS };
